# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="/usr/share/oh-my-zsh"

ZSH_THEME="custom"

plugins=(git)

source $ZSH/oh-my-zsh.sh
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

export LANG=en_GB.UTF-8

# Bash completion
autoload bashcompinit
bashcompinit

# OpenFOAM
export FOAM_INST_DIR=/opt/OpenFOAM
alias ofoam="source ${FOAM_INST_DIR}/OpenFOAM-8/etc/bashrc" # OpenFOAM

# Aliases
#  Colors:
alias ls="ls --color=always"
alias grep="grep --color=always"
alias tree="tree -C"
#  Shortcuts:
alias vi="nvim"
alias vim="nvim"
alias r="ranger"
alias l="ls -lah"
alias g="grep -i"
alias f="kitty +kitten icat" # Display image in kitty terminal
alias clearhist="cat /dev/null > /home/nicola/.zsh_history"
alias fplay="feh -S name --version-sort *" # Open all images in order
alias shu="sudo shutdown -h 0"
pp () {
    python -c "print($1);" # Python-print shortcut
}
mdview () {
    pandoc "$1" -F mermaid-filter -o /tmp/mdview.html
    firefox-developer-edition /tmp/mdview.html
}

# Vi mode terminal
bindkey -v

