# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="/usr/share/oh-my-zsh"

ZSH_THEME="custom"

plugins=(git)

source $ZSH/oh-my-zsh.sh
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

export LANG=en_GB.UTF-8

# Bash completion
autoload bashcompinit
bashcompinit

# Default programs
export EDITOR="nvim"
export TERMINAL="kitty"
export BROWSER="firefox-developer-edition"

# XDG
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export LESSHISTFILE="-"
export GOPATH="$XDG_DATA_HOME"/go

# Environmental fixes
export MOZ_ENABLE_WAYLAND=1
export _JAVA_AWT_WM_NONREPARENTING=1

# Path
export PATH=$GOPATH/bin:$PATH

# OpenFOAM
export FOAM_INST_DIR=/opt/OpenFOAM
alias ofoam="source ${FOAM_INST_DIR}/OpenFOAM-7/etc/bashrc" # OpenFOAM

# Aliases
#  Colors:
alias ls="ls --color=always"
alias grep="grep --color=always"
alias tree="tree -C"
#  Shortcuts:
alias vi="nvim"
alias vim="nvim"
alias r="ranger"
alias l="ls -lah"
alias g="grep -i"
alias f="kitty +kitten icat" # Display image in kitty terminal
alias clearhist="cat /dev/null > /home/nicola/.zsh_history"
alias fplay="feh -S name --version-sort *" # Open all images in order
alias shu="sudo shutdown -h 0"
pp () {
	python -c "print($1);" # Python-print shortcut
}

# Vi mode terminal
bindkey -v
